### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by azhra87** [RatScanner/RatScanner#107]
**Describe the bug**
Window pops up with "Unhandled exception in RatScanner 2.7.0"

**To Reproduce**
1. Click on 'RatScanner.exe"
2. See error

**Screenshots**
![rat](https://user-images.githubusercontent.com/87662237/126189762-72d88328-fa7f-43b1-a4b7-eb06f1d2c2ac.JPG)

**Additional context**
Latest .Net Core Runtime already installed

**Comment by Blightbuster** [comment]
Hey, could you upload the generated `Log.txt` file?

**Comment by Blightbuster** [comment]
Fixed in [v3.1.0](https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0).
Please comment if this issue persists and I will reopen it.
