### ISSUE TITLE
Resolution support 3840X1600

### ISSUE THREAD

**Issue by kThayer2** [RatScanner/RatScanner#115]
Would like ratscanner to support the resolution of 3840X1600
![image](https://user-images.githubusercontent.com/6999856/127777093-f28d5a65-16d7-405a-80aa-81c71d471214.png)

![image](https://user-images.githubusercontent.com/6999856/127777104-96c0d668-c6ac-4edf-b9d2-8dcb0d11c3c2.png)

**Comment by Blightbuster** [comment]
Added in [v2.8.0](https://github.com/RatScanner/RatScanner/releases/tag/v2.8.0)
