### ISSUE TITLE
Good tool, if it would actually detect all Items

### ISSUE THREAD

**Issue by Avnsx** [RatScanner/RatScanner#122]
Was going to use it, but apparently you've not added samples of all images, that  should get detected. Things like a "D size battery", "Broken LCD", "SilencerCo Osprey 9 9x19mm sound supressor" are not getting detected. Playing on WQHD resolution

**Comment by Blightbuster** [comment]
Hey, rat scanner is not using sample images anymore. Could you provide me your `Log.txt` file (after you tried scanning the item without success) as well as a screenshot of at least one of the items that failed?

**Comment by Avnsx** [comment]
> Hey, rat scanner is not using sample images anymore. Could you provide me your `Log.txt` file (after you tried scanning the item without success) as well as a screenshot of at least one of the items that failed?

Nah man that's on you, I don't care enough
