### ISSUE TITLE
Default to Bitcoin on Startup

### ISSUE THREAD

**Issue by XygenSS** [RatScanner/RatScanner#124]
**Is your feature request related to a problem? Please describe.**
Currently the scanner defaults to RAM on launch, and IMO that's a wasted opportunity.

**Describe the feature**
Default to Bitcoin on launch, since it's one of the more sensitive prices that people would like to keep track of

**Additional context**
none

**Comment by Blightbuster** [comment]
Hey, thanks for the suggestion. I really like the idea and will change that with the next update. 👍

**Comment by Blightbuster** [comment]
Changed in v2.8.4
