### ISSUE TITLE
Unknown error, cannot open program

### ISSUE THREAD

**Issue by CaiaTheFireFly** [RatScanner/RatScanner#128]
Heya, not sure if this is an issue with RatScanner or permissions on my PC.

When I try to open RS, the splash icon appears, then shortly after an error pops up. It goes so fast that I don't have time to read it fully. After the error it disappears and is replaced by the Github issue dialog.

From what I can make out, it's saying something about permissions, or cannot read / access the log file (I can't SEE a log file so I assume that's a sign).

Assuming this, I've tried moving the folder to different locations, disabling "Read only" on the folder and contents, and launching as admin. None of that worked, but it should as far as I can tell, there's nothing in the permissions that should be diallowing creation of a file.

**Comment by Blightbuster** [comment]
Hey, first of all sorry for responding this late.
Please, if you still want to, try with the new version [3.1.0](https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0).

Although there werent changes to tackle this specific error, it does have better logging functionality so it will be easier to figure out whats going wrong.

**Comment by Blightbuster** [comment]
Please comment if the issue persists and I will reopen it.
