### ISSUE TITLE
https://api.ratscanner.com flagged and blocked for Phishing

### ISSUE THREAD

**Issue by BrodyHiggerson** [RatScanner/RatScanner#130]
**Describe the bug**
RatScanner fails to open due to Symantec treating https://api.ratscanner.com (108.61.151.169) as a threat. This started today.

**To Reproduce**
1. Have Symantec installed (I know, terrible step - this is on my work machine)
2. Attempt to open RatScanner

**Expected behavior**
RatScanner opens

**Additional context**
```
[SID: 29565] Web Attack: Webpulse Bad Reputation Domain Request attack blocked. Traffic has been blocked for this application: C:\MY_PATH_TO_RATSCANNER\RATSCANNER.EXE

URL: https://api.ratscanner.com
Intensive Protection level: Level 1
URL category: 
	Phishing
```
Reason is:
**Web Attack: Webpulse Bad Reputation Domain Request**

Looks like your domain has been flagged?

**Comment by Blightbuster** [comment]
Hmm when I try to submit the IP for investigation here: https://ipremoval.sms.symantec.com/lookup

It tells me:
> IP 108.61.151.169 does not have any bad reputation

**Comment by BrodyHiggerson** [comment]
The Symantec URL checker seems to flag it: https://sitereview.bluecoat.com/#/lookup-result/https%253A%252F%252Fapi.ratscanner.com

**Comment by Blightbuster** [comment]
Id like to submit the form on the website you provided. Am I right in assuming that the product your using is "Symantec Web Security Service"?

**Comment by Blightbuster** [comment]
Ok they responded in a mail and said, it was now marked as "Not categorised" instead of "Phishing". Please test it out and if it works close the issue :)
