### ISSUE TITLE
Lots of broken wiki links

### ISSUE THREAD

**Issue by spazman5656** [RatScanner/RatScanner#139]
**Describe the bug**
A lot of items link to a non-existent wiki page. It seems for these items the wiki link is using a different name for the item than what appears in game and at the top of RatScanner. For example, the Vltor CASV KeyMod 6 inch rail is called "Vltor CASV KeyMod 6 inch rail" in game, and that is the name that shows at the top of the RatScanner windows, however, when you click the wiki link, it links to "https://escapefromtarkov.fandom.com/wiki/Vltor_CASV_keymod_6_inch_guide" instead of "https://escapefromtarkov.fandom.com/wiki/Vltor_CASV_KeyMod_6_inch_rail". This happens on many different items,

**Comment by Blightbuster** [comment]
Fixed.
Thanks for reporting.
