### ISSUE TITLE
Weapon/Weapon attachment scan doesnt work anymore

### ISSUE THREAD

**Issue by ImBehinYa** [RatScanner/RatScanner#141]
Weapon/Weapon attachment scan doesnt work anymore, if you click on a weapon just the handdrill appears

**To Reproduce**
1. Go to 'fleamarket'
2. Click on 'any weapon'
4. See handdrill or something else but not the weapon with attachment

**Expected behavior**
Show price for weapon+ attachments

**Comment by Blightbuster** [comment]
Hey, unfortunately since August BSG updated the game in a way which from now on makes this feature more or less impossible.
Im open minded about new ways of doing this but for now I will close this issue as a wontfix until I see a possible way to do this again.
