### ISSUE TITLE
.net framework missing after 3.0 update

### ISSUE THREAD

**Issue by DamenQuixotic** [RatScanner/RatScanner#147]
After accepting the new update it told me I needed 6.0 framework. I follow the prompt, install, and it still continues to tell me the framework is missing even after an restart.

**Comment by Blightbuster** [comment]
Hey, please make sure, you have version 6.0.1 of the net framework installed.
I am not certain why yet but apparently version 6.0.0 is not able to run the app.

[Download .Net 6.0.1](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.100-windows-x64-installer)

**Comment by Blightbuster** [comment]
While installing the 6.0.1 SDK will fix the issue, it also installes alot of unescessary development tools which most people dont need.

Instead, id recommend to just install the desktop and asp.net runtime:

[Download .NET 6.0 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.0-windows-x64-installer)
[Download ASP.NET Core 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-hosting-bundle-installer)

If you still cant run the application, you are probably missing the WebView2 Runtime (which should usually come with Edge). 

[Download WebView2 Runtime](https://go.microsoft.com/fwlink/p/?LinkId=2124703)

---

I know all these new dependencis arent a good user experience at all so I'll try my best to cut down on these in the comming updates.

**Comment by DamenQuixotic** [comment]
I did end up going the ASP.NET instead as I thought it a development SDK was a bit overkill. Glad to see you came to the same conclusion.

Either way the main problem is linking to the wrong download from the popup. So as long as people are directed to the right download to get the app working its all good.

**Comment by Blightbuster** [comment]
Unfortunately the popup is nothing I can controll. Id either have to make a standalone installer (which also installs the dependencies) or build the application in standalone mode but that would probably inflate its size to 500mb.

**Comment by Blightbuster** [comment]
Fixed in [v3.1.0](https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0).
You no longer need to install any dependencies.
Please comment if this issue persists and I will reopen it.
