### ISSUE TITLE
Name scanning does not work in borderless mode

### ISSUE THREAD

**Issue by andzno1** [RatScanner/RatScanner#150]
# Description
Name scanning does not yield any result in borderless mode. It works in full screen mode but doesn't show the tooltip (there is a result in the Rat Scanner window). It works as expected with tooltip in windowed mode.

# Versions
* Rat Scanner v3.0.0
* Windows 10 (Build 19042.1348)
* Tarkov 0.12.12.0.16029

**Comment by Blightbuster** [comment]
Hey, please double check that you game is actually in borderless mode when trying to scan. What you describe seems like you flipped borderless and fullscreen mode. Rat Scanner shouldnt be able to work in fullscreen mode but instead only in borderless.

**Comment by andzno1** [comment]
There you go:

https://user-images.githubusercontent.com/4320938/146346288-06984035-206d-4dfe-b197-1e3007dc7820.mp4

**Comment by Blightbuster** [comment]
Oh I see the issue. When you put your game to borderless, it stretches from 1920x1080 to (I assume) 2560x1440. Try to set the resolution inside RatScanner to 2560x1440 (your monitor resolution) and see if that solves the issue.

**Comment by Blightbuster** [comment]
If that doesnt help, it might be related to tarkov upscaling / stretching your 1920x1080 rendered game to 2560x1440

**Comment by andzno1** [comment]
I'll try again. But I think when I did that before, RatScanner changed it back automatically when starting it.

**Comment by Blightbuster** [comment]
Yeah that was a bug in v3.0.0 but it should be fixed in the new version.

**Comment by andzno1** [comment]
> Oh I see the issue. When you put your game to borderless, it stretches from 1920x1080 to (I assume) 2560x1440. Try to set the resolution inside RatScanner to 2560x1440 (your monitor resolution) and see if that solves the issue.

That worked. The setting is now being persisted in RatScanner. Thank you very much.
