### ISSUE TITLE
You must install missing frameworks for .net

### ISSUE THREAD

**Issue by tstricklande39** [RatScanner/RatScanner#152]
**Describe the bug**
I downloaded the framework that was liked in the prompt to update. After installing Ratscanner still says I am missing frameworks. 
**To Reproduce**
Attempt to run.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50135209/145852368-a73f4ba1-11be-4cbb-8b9a-58738ae73441.png)
**Additional context**

**Comment by Blightbuster** [comment]
While installing the 6.0.1 SDK will fix the issue, it also installes alot of unescessary development tools which most people dont need.

Instead, id recommend to just install the desktop and asp.net runtime:

[Download .NET 6.0 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.0-windows-x64-installer)
[Download ASP.NET Core 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-hosting-bundle-installer)

If you still cant run the application, you are probably missing the WebView2 Runtime (which should usually come with Edge). 

[Download WebView2 Runtime](https://go.microsoft.com/fwlink/p/?LinkId=2124703)

---

I know all these new dependencis arent a good user experience at all so I'll try my best to cut down on these in the comming updates.

**Comment by tstricklande39** [comment]
Thank you. Those worked!
