### ISSUE TITLE
Which framework is needed for the new version

### ISSUE THREAD

**Issue by mthp1999** [RatScanner/RatScanner#154]
Just tried to update to the new version, downloaded the x64 desktop and command line versions and it still says i need a new framework.

**Comment by Blightbuster** [comment]
Hey, please have a look here:
https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#rat-scanner-is-not-starting

**Comment by mthp1999** [comment]
Awesome, thank you!

**Comment by andzno1** [comment]
For me only version [6.0.100](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.100-windows-x64-installer) worked.

**Comment by Blightbuster** [comment]
> For me only version [6.0.100](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.100-windows-x64-installer) worked.

While installing the 6.0.1 SDK will fix the issue, it also installes alot of unescessary development tools which most people dont need. Instead I recommed you to install the runtimes listed in the FAQ section manually.

The runtimes listed in the FAQ are the exact same ones which also get installed, when installing the 6.0.100 SDK.

**Comment by cedric888** [comment]
Happened to me to and the only way to solve the problem was to install the SDK version.

**Comment by Blightbuster** [comment]
Fixed in [v3.1.0](https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0).
You no longer need to install any dependencies.
Please comment if this issue persists and I will reopen it.
