### ISSUE TITLE
Allow choice between links opening in overlay vs web browser

### ISSUE THREAD

**Issue by amsmith525** [RatScanner/RatScanner#156]
New overlay looks nice, but does not have my extensions in chrome for privacy / ad removal. Is it possible to disable the overlay and use existing web browser as before update?

**Comment by thaddeus** [comment]
By overlay, I'm assuming you mean the browser when opening Wiki and TarkovTools? If so, yeah, we can probably make it open your default browser for those. As for the actual overlay (what displays items), the only solution we have is WebView2 (based on Edge/Chromium).

**Comment by Blightbuster** [comment]
Changed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
