### ISSUE TITLE
Leaving the Minimal UI creates a new instance of the RatScanner Overlay

### ISSUE THREAD

**Issue by kraffslol** [RatScanner/RatScanner#171]
**Describe the bug**
Every time you leave the minimal UI a new instance of the RatScanner Overlay gets created. This quickly stacks up if you go between the minimal and full UI often.

**To Reproduce**
1. Press the UI toggle button to enter Minimal UI.
2. Go back to the normal UI

**Expected behavior**
I'm guessing it's either supposed to remove the old instance, or reuse it?

**Screenshots**
[https://streamable.com/jt5vck](https://streamable.com/jt5vck)

**Additional context**
Every instance of the overlay is also listed in the alt-tab list.

**Comment by vngst** [comment]
Same here.

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
