### ISSUE TITLE
Windows scaling option, effects the overlay position and size

### ISSUE THREAD

**Issue by Lenkradfreek** [RatScanner/RatScanner#173]
It is shown like 5 cm down and right of the actual item, and I have the correct display resolution selected and it recognizes the items perfeclty.

**Comment by Blightbuster** [comment]
Do you have windows scaling activated? I suspect that being the issue.

**Comment by Lenkradfreek** [comment]
Yes I think so, I made everything bigger because i found it being to small
in 2560x1440 at the beginning

Blightbuster ***@***.***> schrieb am Fr., 17. Dez. 2021,
23:15:
