### ISSUE TITLE
Switch for short price option

### ISSUE THREAD

**Issue by dawidmachon** [RatScanner/RatScanner#174]
Displaying price on max trader as additional option for short price on icon or inspect. Because now flea price is showing - please add option to switch that and maybe third option - show best price = flea/trader

**Comment by Ryuichiro** [comment]
Created a [PR](https://github.com/RatScanner/RatScanner/pull/228) that adds the Trader Price to the tooltip, but I won't invest the time to learn Razor and add the necessary settings. Maybe later when other settings for the new Razor pages were added, so I can copy&paste stuff.

**Comment by Blightbuster** [comment]
Added in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
