### ISSUE TITLE
Allow disable launching tarkov wiki tools in rat scanner 'webview' thing.

### ISSUE THREAD

**Issue by namrog84** [RatScanner/RatScanner#176]
**Describe the feature**
Have a toggle in settings to launch 'external browser' or 'ratscanner browser'.
The internal browser is 'neat', but really not great IMO.

**Additional context**
Tarkov Wiki is terribly redesigned about 6 months ago and so I having an adblockers and a 'wiki fixer' extension,  and its just awful without it.  I'd much much rather it just launch the links in a browser, as opposed to whatever this internal ratscanner browser wrapper is.

**Comment by Blightbuster** [comment]
Changed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
