### ISSUE TITLE
 FIX - Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by obscure37** [RatScanner/RatScanner#239]
I think i just fix the problem with: (Application.Current.DispatcherUnhandledException) after start-up.

Try to download and install this [https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x64-installer](url) 

Its a .NET 6.0 installer - nothing to worry about.

**Comment by SloppyPuppy** [comment]
Try:
cd [Directory of the exe]
start [name.exe]
It appears to have fixed the issue for me

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
