### ISSUE TITLE
Name Scan Mismatches (07.01.2022)

### ISSUE THREAD

**Issue by Ryuichiro** [RatScanner/RatScanner#257]
**Describe the bug**
Some of the new items are not identified correctly by the Name Scan:
- Gas welder safety goggles
- FirstSpear "Strandhogg" plate carrier rig (Ranger Green)
- Sewing Kit
- Medical tools
- Secured magnetic tape cassette

**To Reproduce**
1. Click the magnifier icon in the inspect window of one of the new items.

**Expected behavior**
Query the correct item.

**Screenshots**
![image](https://user-images.githubusercontent.com/4333206/148603433-e7d72ae5-aa9c-434b-9dc4-efc1c814d356.png)
![image](https://user-images.githubusercontent.com/4333206/148602393-d7d90fde-fd1d-4c8f-9815-f85ad82dac75.png)
![image](https://user-images.githubusercontent.com/4333206/148602698-4c4f16f8-39ab-4bbc-b2db-0228f3b7ea96.png)
![image](https://user-images.githubusercontent.com/4333206/148602787-71adce0f-4c66-4803-955c-2b08a9d03983.png)
![image](https://user-images.githubusercontent.com/4333206/148602834-9ba331da-e38d-4956-abcd-f555f763c9df.png)

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
