### ISSUE TITLE
Blacklisted items still show old prices

### ISSUE THREAD

**Issue by Ryuichiro** [RatScanner/RatScanner#264]
**Describe the bug**
Price checks for blacklisted items show old & outdated data.

**To Reproduce**
1. Click the magnifier icon in the inspect window of a blacklisted item.

**Expected behavior**
Not sure if something special should be done for blacklisted items, but I would at least expect a price of 0₽ if no data is available for the last week or so.

**Screenshots**
![RatScanner_09_080852682](https://user-images.githubusercontent.com/4333206/148674489-9e017e24-e04c-4fee-abf1-920e4ff3146e.jpg)

**Blacklisted items as of 0.12.12:**
<details>
<summary>List</summary>
<ul>
    <li>"Rys-T" bulletproof helmet</li>
    <li>Team Wendy EXFIL Ballistic Helmet (Black)</li>
    <li>Vulkan-5 (LShZ-5) bulletproof helmet</li>
    <li>"Altyn" bulletproof helmet</li>
    <li>6B43 6A Zabralo-Sh body armor (0/85)</li>
    <li>NFM THOR Integrated Carrier body armor</li>
    <li>LBT-6094A Slick Plate Carrier</li>
    <li>LBT-6094A Slick Plate Carrier (Tan)</li>
    <li>LBT-6094A Slick Plate Carrier (Olive)</li>
    <li>5.11 Tactical Hexgrid plate carrier</li>
    <li>FORT Redut-T5 body armor</li>
    <li>BNTI Zhuk-6a body armor</li>
    <li>IOTV Gen4 body armor (full protection kit)</li>
    <li>FORT Defender-2 body armor</li>
    <li>NPP KlASS Korund-VM body armor</li>
    <li>IOTV Gen4 body armor (assault kit)</li>
    <li>FORT Redut-M body armor</li>
    <li>IOTV Gen4 body armor (high mobility kit)</li>
    <li>BNTI Gzhel-K armor</li>
    <li>Ars Arma CPC MOD.2 plate carrier rig</li>
    <li>5.11 Tactical TacTec plate carrier rig</li>
    <li>CQC Osprey MK4A plate carrier rig (Protection, MTP)</li>
    <li>WARTECH TV-110 plate carrier rig</li>
    <li>Ars Arma A18 Skanda plate carrier rig</li>
    <li>CQC Osprey MK4A plate carrier rig (Assault, MTP)</li>
    <li>6Sh118 raid backpack</li>
    <li>Mystery Ranch Blackjack 50 backpack (Multicam)</li>
    <li>SSO Attack 2 raid backpack</li>
    <li>Eberlestock F4 Terminator load bearing backpack (Tiger Stripe)</li>
    <li>.45 ACP AP</li>
    <li>7.62x51mm M61</li>
    <li>7.62x51mm M993</li>
    <li>7.62x51mm M62 Tracer</li>
    <li>7.62x54mm R BS gs</li>
    <li>7.62x54mm R BT gzh</li>
    <li>4.6x30mm AP SX</li>
    <li>4.6x30mm Subsonic SX</li>
    <li>5.56x45mm SSA AP</li>
    <li>5.56x45mm M995</li>
    <li>5.56x45mm M855A1</li>
    <li>5.56x45mm M856A1</li>
    <li>7.62x39mm BP gzh</li>
    <li>7.62x39mm MAI AP</li>
    <li>5.45x39mm BS gs</li>
    <li>5.45x39mm PPBS gs "Igolnik"</li>
    <li>5.45x39mm 7N40</li>
    <li>9x19mm AP 6.3</li>
    <li>9x19mm PBP gzh</li>
    <li>5.7x28mm SS190</li>
    <li>5.7x28mm SB193</li>
    <li>12/70 AP-20 slug</li>
    <li>12/70 Copper Sabot Premier HP slug</li>
    <li>12/70 SuperFormance HP slug</li>
    <li>9x39mm BP gs</li>
    <li>9x39mm SPP gs</li>
    <li>40x46mm M441 (HE) grenade</li>
    <li>40x46mm M433 (HEDP) grenade</li>
    <li>23x75mm "Zvezda" flashbang round</li>
    <li>.300 Blackout AP</li>
    <li>.338 Lapua Magnum AP</li>
    <li>FLIR RS-32 2.25-9x 35mm 60Hz thermal rifle scope</li>
    <li>Trijicon REAP-IR thermal scope</li>
    <li>GPNVG-18 Night Vision goggles</li>
    <li>SWORD International Mk-18 .338 LM marksman rifle</li>
    <li>FN40GL Mk2 grenade launcher</li>
    <li>5.56x45 Magpul PMAG D-60 STANAG 60-round magazine</li>
    <li>5.56x45 SureFire MAG5-100 STANAG 100-round magazine</li>
    <li>AK 7.62x39 X Products X-47 50-round drum magazine</li>
    <li>AK 7.62x39 ProMag AK-A-16 73-round drum magazine</li>
    <li>TerraGroup Labs access keycard</li>
</ul>
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
