### ISSUE TITLE
Wrong items sometimes, target coordinates off?

### ISSUE THREAD

**Issue by M3Man03** [RatScanner/RatScanner#30]
So when I try to modifier left click on an item, it doesn't always get the right item or the item at all.  I think this has something to do with it not aiming or getting the right coordinates to the item that I'm clicking on.  The "Resolution" setting seems to affect this greatly. 

I'm using a 3 monitor setup (Left/Center/Right) and Tarkov is in my center monitor, which is classified as #1 in Windows.  Do you think this has something to do with how the program finds the item I'm clicking on?

**Comment by Blightbuster** [comment]
The monitor your using should not matter as long as the resolution is set correctly inside rat scanner.
As far as icon scanning goes:
Its not perfect (yet 😄) and still has some known issues which you are probably experiencing right now.
More on that here: https://github.com/Blightbuster/RatScanner/blob/master/FAQ.md#icon-scanning-gets-a-lot-of-wrong-matches

**Comment by M3Man03** [comment]
Its completely inconsistent.  Sometimes it'll find the item, sometimes nothing comes up at all and other times it comes up with an item no where near what the item is I'm clicking on.

How do I go about troubleshooting this?

**Comment by Blightbuster** [comment]
> Also, my screen resolution is 2560x1080 since I'm on a widescreen. The QHD doesn't seem to match and the FHD seems to work better. Why not allow users to put in their own resolutions rather than selecting from a list which may not have the right one?
The problem is that every resolution I add needs some custom configuration as there are other things then screensize needed.
Since your using 2560x1080 (FHD UltraWide) the FHD option is optimal for you since the horizontal makes no difference to the game (some exceptions).

> How do I go about troubleshooting this?
Could you maybe make a recording of your screen demonstrating the behaviour or make some screenshots and provide them to me either here or on discord?

**Comment by Manevolent** [comment]
If it helps, I noticed the same issues on my end, but the "inaccuracy" seems to be occurring when the in-game hovered tool-tip, which displays the item name, is present on top of the item desired to be identified.  Try moving your mouse slowly through the item and Shift-Clicking; as I did this and slowly moved down the item, occluding different sections of it, the results changed.  I am pretty sure those pixels being on the framebuffer are throwing off the recognition, which I might add is honestly a really neat idea.  It just might be getting thrown off by having partial sections of the whole icon being covered.

**Comment by M3Man03** [comment]
I tried to record it via nVidia's instant replay but the tooltip doesn't seem to be part of the game, so it doesn't get recorded.  

I don't know how else to explain it other than its not accurate or consistent.  Rarely will I get the correct item when clicking on it and clicking in approximately the same location seems to produce different results.  It just really seems that the accuracy of what I'm clicking on is off.

**Comment by Blightbuster** [comment]
If you have shadow play, it should record it just fine.

**Comment by Blightbuster** [comment]
Please reopen this issue, when you have more detail / a video showing this behaviour.
