### ISSUE TITLE
Name scan doesn't work

### ISSUE THREAD

**Issue by k0ff1l** [RatScanner/RatScanner#336]
Clicking on magnify and name scanning doesn't just work

1440x900, Borderless mode, Scan language: Russian

**Comment by Blightbuster** [comment]
Hey, could you please attach a image of a inspection window which can be used to reproduce this issue?

**Comment by k0ff1l** [comment]
> Hey, could you please attach a image of a inspection window which can be used to reproduce this issue?

like this ? 
![image](https://user-images.githubusercontent.com/58639180/152635435-9f0ecc73-3c66-493f-b4fa-9f4fdbd21731.png)

didn't really understood what to screen...

**Comment by k0ff1l** [comment]
![image](https://user-images.githubusercontent.com/58639180/152635726-3f992ccc-ad26-4b59-ac68-4322992410f2.png)
it just gives no price

**Comment by k0ff1l** [comment]
[NameScan]
enable=True
language=13
[IconScan]
enable=True
scanrotatedicons=True
hotkeykeyboard=LeftShift
hotkeymouse=Left
usecachedicons=True
[ToolTip]
duration=1500
digitgroupingsymbol=.
[MinimalUi]
showname=True
showavgdayprice=True
showpriceperslot=True
showtraderprice=True
showtradermaxprice=True
showupdated=False
showquesthideouttracker=False
showquesthideoutteamtracker=False
opacity=10
[Tracking]
shownonfirneeds=True
[TarkovTracker]
token=
showteam=True
[Other]
screenwidth=1440
screenheight=900
minimizetotray=False
alwaysontop=True
itemdatabundleversion=20220118
logdebug=True
configversion=2


Settings

**Comment by Blightbuster** [comment]
> > Hey, could you please attach a image of a inspection window which can be used to reproduce this issue?
> 
> like this ? 
> ![image](https://user-images.githubusercontent.com/58639180/152635435-9f0ecc73-3c66-493f-b4fa-9f4fdbd21731.png)
> 
> didn't really understood what to screen...
> 
> 

Yes thanks 👍

**Comment by Blightbuster** [comment]
Hey, sorry for the late response. You can fix it by setting your resolution in rat scanner to 1540x900 instead of 1440x900.
I dont think I will push an actual fix for it downstream since it's an issue which requires a lot of time and only affects very few people.

**Comment by Blightbuster** [comment]
Closing as stale.
