### ISSUE TITLE
Integration with tarkov-market.com

### ISSUE THREAD

**Issue by vvanouytsel** [RatScanner/RatScanner#354]
**Is your feature request related to a problem? Please describe.**
Since Tarkov Tools is offline due to the ongoing situation in the world, it might be handy to have the possibility to use an alternative third party application for retrieving the flea market prices. Tarkov Market could be one of those alternatives.

**Comment by Blightbuster** [comment]
I'll close this since the backend recently was moved over to use [tarkov.dev](https://tarkov.dev/)
