### ISSUE TITLE
Allow more choice for the "Icon scan modifier"-key within the GUI

### ISSUE THREAD

**Issue by gcatellani** [RatScanner/RatScanner#37]
Allow any or at least more (modifier) keys to be set for the "Icon scan modifier" feature using Ratscanner's GUI.
This most probably relates to [this card](https://github.com/Blightbuster/RatScanner/projects/2#card-46671849)

Some background for where the request stems from: I already use ALT, CTRL and SHIFT + LMB in Tarkov for different actions and thus collides with Ratscanner's functionality.

P.S.: please let us now the moment a BSG employee confirms the tool won't get us banned, so I may finally use your awesome tool. Still made you a small donation via Patreon covering nearly a year worth of your Mouse-plan as a thank you for your dedication and the work you put into the tool, regardless of whether I use it at the moment or not. Much appreciated.

**Comment by Blightbuster** [comment]
Added in 2.5.0
