### ISSUE TITLE
Minimal UI broken on 3.3.1

### ISSUE THREAD

**Issue by aVitomin** [RatScanner/RatScanner#386]
![image](https://user-images.githubusercontent.com/11780299/177008458-281283c3-4713-4574-9d50-232075644a7d.png)

![image](https://user-images.githubusercontent.com/11780299/177008451-5479faca-5bab-42d7-8d83-0716b5ac8c73.png)

**Comment by Blightbuster** [comment]
Thanks for submitting the issue. I won't be able to fix for the next few hours.

If you rely on the minimal ui overlay, you can manually downgrade to the previous version by downloading it from the release section here on GitHub.
