### ISSUE TITLE
Add always on scanning instead of needing to click on the magnifying glass

### ISSUE THREAD

**Issue by greensmyname** [RatScanner/RatScanner#4]
Would be cool if there was always on scanning so the price would pop up upon inspecting an item instead of needing to click on the magnifying glass.

This would cause issue due to the magnifying glass on the screen where you invite friends to your raid group, so i suggest scanning for any constant text element on that screen every 5 seconds to temporarily stop auto scanning until it detects it's no longer there. Constant text elements on that screen include the text "PREPARE TO ESCAPE", "CONFIRMATION", "CURRENT INGAME TIME:", "CURRENT WEATHER CONDITIONS:", "Find username", "GROUP", "YOUR MAIN CHARACTER", "START LOOKING FOR A GROUP", "STOP LOOKING FOR GROUP", "READY" and "BACK"

This is also probably not that large of an issue because you won't really be spending a lot of time there, and wont be needing to use the price tool on that screen, so incorrect scans there wouldn't be that problematic.

![lobby screen](https://user-images.githubusercontent.com/68490933/93951414-43fc4180-fd14-11ea-8d6c-48a0b8edf3f2.png)

**Comment by Blightbuster** [comment]
Thanks for suggesting this feature, it has since been added in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
