### ISSUE TITLE
Loading of Market Data Failed

### ISSUE THREAD

**Issue by NCaburis** [RatScanner/RatScanner#411]
On start, UI loads and then goes to error right away. Issue persists if running as admin.

![image](https://user-images.githubusercontent.com/26880558/184178684-d5c624ef-773f-41bc-86bc-e15c8afbef20.png)

**Comment by Dogrtt** [comment]
Confirming

**Comment by mavakon** [comment]
Yep, same

**Comment by greyhammer** [comment]
Same

**Comment by LDzonis** [comment]
same

**Comment by Blightbuster** [comment]
Fixed, thanks for reporting.
