### ISSUE TITLE
Github Issue Track Redirect 'URL Too Long'

### ISSUE THREAD

**Issue by NCaburis** [RatScanner/RatScanner#412]
The redirect prompt box when RatTracker crashes generates a URL that is too long, causing github to return an error 414—URI too long.

Related Github Doc: [Here](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query)

**Comment by NCaburis** [comment]
This is the URL that caused the issue:

https://github.com/RatScanner/RatScanner/issues/new?body=**Error**%0ALoading+of+market+data+failed.%0ANewtonsoft.Json.JsonSerializationException%3A+Error+converting+value+%7Bnull%7D+to+type+%27System.Int32%27.+Path+%27%5B9%5D.avg24hPrice%27%2C+line+1%2C+position+4849.%0D%0A+---%3E+System.InvalidCastException%3A+Null+object+cannot+be+converted+to+a+value+type.%0D%0A+++at+System.Convert.ChangeType(Object+value%2C+Type+conversionType%2C+IFormatProvider+provider)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader+reader%2C+Object+value%2C+CultureInfo+culture%2C+JsonContract+contract%2C+Type+targetType)%0D%0A+++---+End+of+inner+exception+stack+trace+---%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader+reader%2C+Object+value%2C+CultureInfo+culture%2C+JsonContract+contract%2C+Type+targetType)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract+contract%2C+JsonProperty+containerProperty%2C+JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader+reader%2C+JsonObjectContract+contract%2C+JsonProperty+containerProperty%2C+ObjectConstructor%601+creator%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader+reader%2C+JsonObjectContract+objectContract%2C+JsonProperty+containerMember%2C+JsonProperty+containerProperty%2C+String+id%2C+Boolean%26+createdFromNonDefaultCreator)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList+list%2C+JsonReader+reader%2C+JsonArrayContract+contract%2C+JsonProperty+containerProperty%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+Object+existingValue%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader+reader%2C+Type+objectType%2C+Boolean+checkAdditionalContent)%0D%0A+++at+Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.JsonConvert.DeserializeObject(String+value%2C+Type+type%2C+JsonSerializerSettings+settings)%0D%0A+++at+Newtonsoft.Json.JsonConvert.DeserializeObject%5BT%5D(String+value%2C+JsonSerializerSettings+settings)%0D%0A+++at+Newtonsoft.Json.JsonConvert.DeserializeObject%5BT%5D(String+value)%0D%0A+++at+RatScanner.ApiManager.GetMarketDB()%0A%3Cdetails%3E%0A%3Csummary%3ELog%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5B16%3A17%3A07.8430391%5D+%3E+%5BInfo%5D++-----+RatScanner+3.3.5+-----%0A%5B16%3A17%3A07.8431995%5D+%3E+%5BInfo%5D++Starting+RatScanner...%0A%5B16%3A17%3A07.8432020%5D+%3E+%5BInfo%5D++Loading+config...%0A%5B16%3A17%3A07.8450130%5D+%3E+%5BInfo%5D++Setting+temporary+default+item...%0A%5B16%3A17%3A07.8461525%5D+%3E+%5BInfo%5D++Checking+for+item+data+updates...%0A%5B16%3A17%3A07.8483822%5D+%3E+%5BInfo%5D++Loading+resource+%22RSItemDataBundleVersion%22...%0A%5B16%3A17%3A08.0737403%5D+%3E+%5BInfo%5D++Initializing+tarkov+tracker+database%0A%5B16%3A17%3A08.0738687%5D+%3E+%5BInfo%5D++Initializing+hotkey+manager...%0A%5B16%3A17%3A08.0760489%5D+%3E+%5BInfo%5D++UI+Ready!%0A%5B16%3A17%3A09.0859463%5D+%3E+%5BInfo%5D++Checking+for+updates...%0A%5B16%3A17%3A09.0862634%5D+%3E+%5BInfo%5D++Loading+resource+%22RSClientVersion%22...%0A%5B16%3A17%3A09.1080175%5D+%3E+%5BInfo%5D++Loading+progress+data...%0A%5B16%3A17%3A09.3131155%5D+%3E+%5BInfo%5D++Loading+price+data...%0A%5B16%3A17%3A09.4143132%5D+%3E+%5BError%5D+Loading+of+market+data+failed.%0ANewtonsoft.Json.JsonSerializationException%3A+Error+converting+value+%7Bnull%7D+to+type+%27System.Int32%27.+Path+%27%5B9%5D.avg24hPrice%27%2C+line+1%2C+position+4849.%0D%0A+---%3E+System.InvalidCastException%3A+Null+object+cannot+be+converted+to+a+value+type.%0D%0A+++at+System.Convert.ChangeType(Object+value%2C+Type+conversionType%2C+IFormatProvider+provider)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader+reader%2C+Object+value%2C+CultureInfo+culture%2C+JsonContract+contract%2C+Type+targetType)%0D%0A+++---+End+of+inner+exception+stack+trace+---%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader+reader%2C+Object+value%2C+CultureInfo+culture%2C+JsonContract+contract%2C+Type+targetType)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract+contract%2C+JsonProperty+containerProperty%2C+JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader+reader%2C+JsonObjectContract+contract%2C+JsonProperty+containerProperty%2C+ObjectConstructor%601+creator%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader+reader%2C+JsonObjectContract+objectContract%2C+JsonProperty+containerMember%2C+JsonProperty+containerProperty%2C+String+id%2C+Boolean%26+createdFromNonDefaultCreator)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.Json%0A%60%60%60%0A%3C%2Fdetails%3E&title=Loading+of+market+data+failed.%0ANewtonsoft.Json.JsonSerializationException%3A+Error+converting+value+%7Bnull%7D+to+type+%27System.Int32%27.+Path+%27%5B9%5D.avg24hPrice%27%2C+line+1%2C+position+4849.%0D%0A+---%3E+System.InvalidCastException%3A+Null+object+cannot+be+converted+to+a+value+type.%0D%0A+++at+System.Convert.ChangeType(Object+value%2C+Type+conversionType%2C+IFormatProvider+provider)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader+reader%2C+Object+value%2C+CultureInfo+culture%2C+JsonContract+contract%2C+Type+targetType)%0D%0A+++---+End+of+inner+exception+stack+trace+---%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader+reader%2C+Object+value%2C+CultureInfo+culture%2C+JsonContract+contract%2C+Type+targetType)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract+contract%2C+JsonProperty+containerProperty%2C+JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader+reader%2C+JsonObjectContract+contract%2C+JsonProperty+containerProperty%2C+ObjectConstructor%601+creator%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader+reader%2C+JsonObjectContract+objectContract%2C+JsonProperty+containerMember%2C+JsonProperty+containerProperty%2C+String+id%2C+Boolean%26+createdFromNonDefaultCreator)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList+list%2C+JsonReader+reader%2C+JsonArrayContract+contract%2C+JsonProperty+containerProperty%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+Object+existingValue%2C+String+id)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader+reader%2C+Type+objectType%2C+JsonContract+contract%2C+JsonProperty+member%2C+JsonContainerContract+containerContract%2C+JsonProperty+containerMember%2C+Object+existingValue)%0D%0A+++at+Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader+reader%2C+Type+objectType%2C+Boolean+checkAdditionalContent)%0D%0A+++at+Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader+reader%2C+Type+objectType)%0D%0A+++at+Newtonsoft.Json.JsonConvert.DeserializeObject(String+value%2C+Type+type%2C+JsonSerializerSettings+settings)%0D%0A+++at+Newtonsoft.Json.JsonConvert.DeserializeObject%5BT%5D(String+value%2C+JsonSerializerSettings+settings)%0D%0A+++at+Newtonsoft.Json.JsonConvert.DeserializeObject%5BT%5D(String+value)%0D%0A+++at+RatScanner.ApiManager.GetMarketDB()&labels=bug

**Comment by Blightbuster** [comment]
Hey, thanks for submitting the issue. It has since been fixed in more recent version of Rat Scanner.
