### ISSUE TITLE
Downloading of file ItemData failed

### ISSUE THREAD

**Issue by maxpull** [RatScanner/RatScanner#416]
Updated to 336 this morning and I have been having this error:
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.

Re-downloaded 335, same issue.

**Comment by Sleuthman** [comment]
Me too, getting some error, redownloaded and re-installed, same thing.

**Comment by Sleuthman** [comment]
Working for me now
