### ISSUE TITLE
Widespread ID/Detection Mismatches

### ISSUE THREAD

**Issue by Kanzuke117** [RatScanner/RatScanner#421]
With the new 3.3.6 version, I'm now getting lots of incorrect name lookups:

Secure Flash Drive -> Secure Flash Drive (quest item)
Canister with Purified Water -> Water pump operation data (quest item)
Graphics Card -> Package of Graphics Cards (quest item)
Rat Cola -> Tarcola
UHF RFID -> Wifi Camera
42 Signature English Tea -> Signal Flare White
Tank Battery -> Military Cable
Whiskey -> Vodka (t.dev lookup uses incorrect ID as well it seems)
Bundle of Wires -> Benelli M3 Forend
Can of Sprats -> Chainlet
Capacitors -> Can of Pacific Saury
Fuel Conditioner -> Rye Croutons
L1 Injector -> Adrenaline
Melodonin -> Adrenaline
Obdolbos -> SJ9 
AHF1-M - SJ9
Mule -> SJ9
Pile of Meds -> Piece of Plexiglass
Power Cord -> Wooden Clock
Propane -> Neoprene Mask
Antique Vase -> Ammunition Case

The EyeLog suggests the OCR is working fine, so I assume whatever translation from Name to item ID is to blame, perhaps an out of date database?

[Log.txt](https://github.com/RatScanner/RatScanner/files/9432231/Log.txt)
[RatEyeLog.txt](https://github.com/RatScanner/RatScanner/files/9432232/RatEyeLog.txt)

**Comment by Blightbuster** [comment]
The issue was that I removed all quest items from the DB but used an extension method from the quest tracking stuff which returned true if the item was used in a quest (like cpu's or salewa) and not just if it was an actual quest item (like the golden pocket watch). Thanks for reporting btw :)
