### ISSUE TITLE
[Error] Loading of resource "RSItemDataBundleVersion" failed.

### ISSUE THREAD

**Issue by Holeur** [RatScanner/RatScanner#448]
**Describe the bug**
I trying to start ratscanner and appear this error

**Screenshots**
![image](https://user-images.githubusercontent.com/28985524/210152584-f7f2f718-768a-4874-aad3-9ed0ee9d6429.png)

**Additional context**

**Log file content**
[Log.txt](https://github.com/RatScanner/RatScanner/files/10327822/Log.txt)

**Comment by Blightbuster** [comment]
Do you still get this error or was it just that time? Seems like an issue with your firewall from what I can see in the log file.

**Comment by Blightbuster** [comment]
Fixed in backend. Thanks for reporting.
