### ISSUE TITLE
Discord streams stops working when using Ratscanner

### ISSUE THREAD

**Issue by morb81** [RatScanner/RatScanner#460]
**Describe the bug**
Discord streams stops working when using Ratscanner
Participants cannot see the live stream anymore as soon as i open Ratscanner.

**To Reproduce**
Simple, open up ratscanner when streaming on Discord.

**Expected behavior**
Streaming should not stop working. :)

`

**Comment by Blightbuster** [comment]
This was supposedly fixed in a previous version but seems like it's broken again... I'll try to check if anything changed about the fix and why it doesnt work anymore.

In the mean time, you can just stream your screen instead of the window which should fix it.

**Comment by Blightbuster** [comment]
Just tested again and it seems to not be an issue. Pls comment if you still experience the issue so I can do further testing.
