### ISSUE TITLE
Icon Sanning and Hotkeys not working with QHD monitors

### ISSUE THREAD

**Issue by Percy2Live** [RatScanner/RatScanner#461]
This bug is linked to the old bugs #25 and #19 , it seems these issues popped up again with the latest version 3.4.1

**To Reproduce**
Use a QHD Monitor (2560x1440)

**Expected behavior**
The picture scanning doesn't work, only the name scanning. The hotkey isn't working in general (probably because it relys on the image scan). Debug says everything's fine. When disabling the name scanning, ratscanner stops working at all.

**Comment by Blightbuster** [comment]
This has been fixed in a recent version of RatEye by using a new image processing algorithm.
