### ISSUE TITLE
Hideout required item calculation is wrong

### ISSUE THREAD

**Issue by christallire** [RatScanner/RatScanner#462]
**Describe the bug**
Hideout required item calculation is wrong

https://github.com/RatScanner/RatScanner/blob/7ead3a95f56efc5e576ab8d5d80a17156e725d42/RatScanner/ViewModel/MenuVM.cs#L266-L301

requirement.HideoutPartId is ItemId
progress.HideoutParts is PartId
so result of `var hideoutPart = progress.HideoutParts.Find(x => x.Id == requirement.HideoutPartId); ` is always null so it can't be found

I've tried to fix the bug but can't be fixed because NeededItem is coupled with many logics so it requires refactoring

**Comment by christallire** [comment]
@thaddeus could you please have a look? thanks!

**Comment by Blightbuster** [comment]
This should be fixed with f6b8cfaf896257277d391ed010ed42d5a1c5ef2c but there is also (still?) an issue with the tarkovtracker.io API which causes the stash upgrade costs to be taken into account when the user selected that he has the EoD edition.

**Comment by christallire** [comment]
I'm not sure we're on the same page. I personally fixed the issue without accumulating the needed item (hideoutPart.Count;)

```
	private static (int need, int have) GetHideoutRequired(IEnumerable<HideoutItem> requiredHideoutItems, UserProgress progress)
	{
		var need = 0;
		var have = 0;

		// Add up all the hideout requirements
		foreach (var requirement in requiredHideoutItems)
		{
			need += requirement.Needed;

			if (progress == null)
				continue;

			var moduleId = requirement.ModuleId;
			var module = progress.HideoutModules.FirstOrDefault(e => e.Id == moduleId);

			// Check if the requirement hideout part id exists in progress.HideoutParts
			if (module?.Complete == true)
				have += requirement.Needed;
		}

		return (need, have);
	}
```

**Comment by christallire** [comment]
fix of another half requires 

https://github.com/RatScanner/RatScanner/blob/7ead3a95f56efc5e576ab8d5d80a17156e725d42/RatTracking/FetchModels/tarkovdev/HideoutStations.cs#L88

This is wrong but used and propagated so many codes so can't be fixed

https://github.com/RatScanner/RatScanner/blob/7ead3a95f56efc5e576ab8d5d80a17156e725d42/RatTracking/FetchModels/tarkovdev/HideoutStations.cs#L70-L71

This is correct value and should be propagated

**Comment by christallire** [comment]
thanks!
