### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by Thebrider** [RatScanner/RatScanner#464]
When I run the program, after a while FPS drops to almost nothing, and when I minimize the game and then open it, FPS increases to normal, but soon falls down again, what to do?

**Comment by Blightbuster** [comment]
I'm pretty sure your experiencing a memory leak issue of tarkov (quite a few have that) which is not related to rat scanner.

**Comment by Blightbuster** [comment]
I'm pretty sure your experiencing a memory leak issue of tarkov (quite a few have that) which is not related to rat scanner.

**Comment by Thebrider** [comment]
Nah, I've already solved that problem (turning off SYNC)
