### ISSUE TITLE
Scanner works partially or poorly on QHD

### ISSUE THREAD

**Issue by Zumbzaq** [RatScanner/RatScanner#465]
**Describe the bug**
I only get icon scanning to work in specific parts of the screen, namely in the middle and right side of the screen, and only then 70% of the items i scan work, while maybe 20% of those, scan a different item. Sidenote; Fullscreen seems to be viable if you have a seconday mirror to keep your rat scanner on. This is tested with and without HDR, in borderless and fullscreen.

**Comment by Kroktar** [comment]
Hi, i upgraded from 3840x1080 to 3440x1440 and i can confurm UQHD is also not working.
Thanks for this app btw.

**Comment by Blightbuster** [comment]
Tracking in #461
