### ISSUE TITLE
Best Trader doesn't match

### ISSUE THREAD

**Issue by I2evard** [RatScanner/RatScanner#498]
I tried to sell my key to Fence since it seemed to be more worth for him and I realised that he wasn't able to buy any keys anymore. I don't know if its new, but currently the best Trader would be Therapist 

1. Buy RB-AO key from flea market
2. Press on "Left-Shift" + "Left-Click" on the item (Notice best Trader being Fence)
4. Click on "Traders"
5. Select the Fence
6. Notice that the key is grayed and cannot be sold

**Expected behavior**
The right "Best Trader" should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/47044376/223517397-afa0a094-dcc0-4098-a7a4-039558ea8814.png)

**Comment by Blightbuster** [comment]
Oh yea, thats an issue with the backend, not clearing old trader data. Thanks for reporting 👍

**Comment by SupremeTele** [comment]
yeah, i also wanted to sell the Health Resort west wing room 309 key for 27k to fence....

**Comment by Blightbuster** [comment]
Fixed in a recent update by switching to a new backend.
