### ISSUE TITLE
Scanning does not work

### ISSUE THREAD

**Issue by PiakYourNaiTou** [RatScanner/RatScanner#54]
Running EFT on borderless and windowed with RatScanner running. I set Alt as my scan modifier and whenever I do Alt + Left click, the price of the item does not display onto the UI. It always has RAM on display. Have already cleared Icon cache folder to see if it resolves the issue but to no avail. Resolution has also been changed to the one used in game 1920x1080.

**Comment by C3ntraX** [comment]
Same problem here. Shift Key used. 1920x1080. But it seems, that the tool does something, when I spam the key, it randomly freezes my chrome explorer. Folder also cleaned. It always stays at "RAM"

**Comment by Blightbuster** [comment]
Solved by running ratscanner.exe as admin.
