### ISSUE TITLE
The app is not staying on top of Tarkov

### ISSUE THREAD

**Issue by vedo1608** [RatScanner/RatScanner#59]
**Describe the bug**
I am not really sure when this started happening, I think it started with the last Tarkov update two days ago, the small one for the launcher. The RatScanner app is staying on top of all the other app windows but does not stay on top of Escape from Tarkov.

**To Reproduce**
Open RatScanner, open Tarkov, RatScanner is not visible. Works vice versa too, open Tarkov, open RatScanner, it is not visible.

**Expected behavior**
Should be on top of every app.

**Screenshots**

**Additional context**

**Log file content**
```
Replace this with the content of your log file.
```

**Comment by Blightbuster** [comment]
Im not able to reproduce this. Are you sure that your game is not in fullscreen? Maybe the latest launcher update reset some settings.

**Comment by vedo1608** [comment]
damn, it did. I'm sorry I didn't check that first.

**Comment by Blightbuster** [comment]
All good 👍
