### ISSUE TITLE
**Error** One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _temp

### ISSUE THREAD

**Issue by hnlee1234** [RatScanner/RatScanner#590]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _temp

**Comment by Blightbuster** [comment]
Fixed in v3.6.5
