### ISSUE TITLE
Gunpowder "Kite" wiki link opens an empty page

### ISSUE THREAD

**Issue by vedo1608** [RatScanner/RatScanner#61]
**Describe the bug**
When inspecting the Gunpowder "Kite", and clicking on "Wiki" link in the app window, an empty page is opened. The app opens https://escapefromtarkov.gamepedia.com/Gunpowder_Kite but should open https://escapefromtarkov.gamepedia.com/Gunpowder_%22Kite%22 or https://escapefromtarkov.gamepedia.com/Gunpowder_"Kite"

**To Reproduce**
When inspecting the Gunpowder "Kite", and clicking on "Wiki" link in the app window, an empty page is opened. The app opens https://escapefromtarkov.gamepedia.com/Gunpowder_Kite but should open https://escapefromtarkov.gamepedia.com/Gunpowder_%22Kite%22 or https://escapefromtarkov.gamepedia.com/Gunpowder_"Kite"

**Expected behavior**
https://escapefromtarkov.gamepedia.com/Gunpowder_"Kite" should be opened

**Screenshots**
![tarkov1](https://user-images.githubusercontent.com/1207004/104371075-e472ad80-551f-11eb-8642-ef42928f7f1f.png)
![tarkov2](https://user-images.githubusercontent.com/1207004/104371108-e6d50780-551f-11eb-9cdf-7a12160868cc.png)

**Additional context**

**Log file content**
```
Replace this with the content of your log file.
```

**Comment by Blightbuster** [comment]
Thanks for reporting. Im able to reproduce this!

The api returns the correct url so it seems to be a bug with parsing / opening the url.
![image](https://user-images.githubusercontent.com/24388294/104382729-edb74680-552e-11eb-9fb4-742bf2f47a82.png)

**Comment by Blightbuster** [comment]
https://github.com/RatScanner/RatScanner/blob/992aca646084d964b9b46434180dff41b2da6533/RatScanner/View/MainMenu.xaml.cs#L22

Seems like the used way to invoke a new url-open request is unable to handle some encoding.

Using something like this will fix it.
```c#
var psi = new ProcessStartInfo
{
	FileName = e.Uri.ToString(),
	UseShellExecute = true
};
Process.Start(psi);```
