### ISSUE TITLE
Icons stuck at loading when using Ratscanner

### ISSUE THREAD

**Issue by C4LLZ** [RatScanner/RatScanner#63]
**Describe the bug**
When using the Ratscanner icons in Tarkov don't load properly. 

**To Reproduce**

Happens when I open Ratscanner and use it for a bit. (Even in raids)

**Screenshots**
![image](https://user-images.githubusercontent.com/33510329/104749352-00aa6080-5753-11eb-92b2-f0d82bf11b3d.png)

**Additional context**
To get around this I just need to clear Cache but then I need to close Tarkov and if it happens in a raid I can't do anything about it.

**Comment by Blightbuster** [comment]
hmm seems to be an issue with ratscanner and tarkov fighting over the cache files... on the one hand ratscanner needs to read the cache to be able to scan icons, on the other hand eft needs to write to the cache for obvious reasons. I'll have to investigate if tarkov need's / want's exclusive write on the cache or if it would be possible to do writing and reading at the same time.

**Comment by cafeoh** [comment]
This issue still isn't fixed for me. When rat scanner is opened (even when the "use cached icons" is unselected), icons very often won't load for extended periods of times. Icons load just fine when rat scanner isn't started.
