### ISSUE TITLE
PvE Toggle/Mode

### ISSUE THREAD

**Issue by FuturamaPhill** [RatScanner/RatScanner#648]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature**
A way of switching to the PvE flea instead of PvP as the economies are very different

**Additional context**
Not sure if this is possible as unsure of the api links into PvE just thought it would be a useful feature

**Comment by rmscode** [comment]
Tarkov.dev recently added the PvE flea! Do you guys have a timeline on adding this enhancement?

**Comment by Ryuichiro** [comment]
Before adding an option for this to the client we would need a second [MarketAPIServer](https://github.com/RatScanner/MarketAPIServer) which must be configured to query PVE data or the existing server would need to be expanded to provide both Regular and PVE data. I never looked at the Server project before, so I don't know how easy/hard such a change would be.

**Comment by Blightbuster** [comment]
Yep exactly. However proxying prices through the MarketAPIServer isnt really nescessary anymore hence Im currently trying to move over everything to directly use the tarkov.dev graphql api. You can check the progress on the dev branch but its a rather crippling thing to do unfortunately.

**Comment by ralfisalhon** [comment]
Looking forward to the toggle being merged in. I see the API has been updated with the Market API Server!

**Comment by Blightbuster** [comment]
Added in latest release.
