### ISSUE TITLE
Shift, Control, Alt

### ISSUE THREAD

**Issue by King-Joey** [RatScanner/RatScanner#67]
The problem is that I use the 3 keybind combos on my day-to-day Tarkov experience.
Shift: hold breath
Ctrl: to quick loot
Alt: to quick equip

If I use the RatScanner hotkey with any of those I will;
Shift: not shoot my enemy and die.
Ctrl: not be able to quick loot someone I've killed and get killed for being a vulnerable position for far too long dragging every item over.
Alt: not being able to quickly insurance fraud or equip better gear if mine got shredded from a cqc exchange and die.

I would like to see the hotkey command be customizable to the user, for me personally I would use tilda or alt+tilda. But if that is far more complicated than it needs to be I would be 100% satisfied if I could disable the hotkeys and only use the magnifying lens in the top left corner after inspecting the item.

Please let me know if this request is confusing or I may need to explain my problem better. Thank you for making this, I really hope I can use it soon!

**Comment by Blightbuster** [comment]
Added in 2.5.1
