### ISSUE TITLE
Is a custom resolution option possible?

### ISSUE THREAD

**Issue by doctor-nick** [RatScanner/RatScanner#77]
I'm enjoying the tool, but I recently upgraded my monitor to a new 3840x1600 ultrawide display. Unfortunately, it's not currently an option. Is it possible to set a custom resolution?

**Comment by Blightbuster** [comment]
Hey, right now there is no support for custom resolutions but it will come with the next major version for which I unfortunately dont have a ETA yet.

**Comment by Blightbuster** [comment]
Added in [v2.8.0](https://github.com/RatScanner/RatScanner/releases/tag/v2.8.0)
