### ISSUE TITLE
Is this concidered cheating?

### ISSUE THREAD

**Issue by alexjshepler** [RatScanner/RatScanner#78]
I want to use this but I don't' want to get banned for cheating.

**Comment by Blightbuster** [comment]
Hey, please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#can-i-get-banned-for-using-rat-scanner).

**Comment by DoogeJ** [comment]
> Hey, please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#can-i-get-banned-for-using-rat-scanner).

Someone asked the EFT Discord moderators earlier this week, and they said using RatScanner is considered a bannable offense.
Might want to double-check with them.

**Comment by Blightbuster** [comment]
I just read up on the last few messages on the eft discord. To me it looks like they did not have a look at how rat scanner works or even what it is. Just a quick copy paste answer without looking at any details. I'll try to get in contact with them, maybe they can help to get some official response. Thanks for sharing btw 👍

**Comment by DoogeJ** [comment]
@Blightbuster did you ever get some official response? :)

**Comment by Blightbuster** [comment]
> @Blightbuster did you ever get some official response? :)

Indeed they did. Have a look here:
https://www.github.com/RatScanner/RatScanner/tree/master/FAQ.md

**Comment by DoogeJ** [comment]
@Blightbuster thank you so much!

**Comment by vaisest** [comment]
> > @Blightbuster did you ever get some official response? :)
> 
> Indeed they did. Have a look here: https://www.github.com/RatScanner/RatScanner/tree/master/FAQ.md

The response has since been removed. Has the answer to this question changed?

**Comment by Blightbuster** [comment]
> > > @Blightbuster did you ever get some official response? :)
> > 
> > 
> > Indeed they did. Have a look here: https://www.github.com/RatScanner/RatScanner/tree/master/FAQ.md
> 
> The response has since been removed. Has the answer to this question changed?

Hey, the answer has not change. It got removed after I was approached by a BSG official who kindly asked me to remove the quote as they saw it as to much of an affiliation.
