### ISSUE TITLE
NetCore Not Found

### ISSUE THREAD

**Issue by BlueTrademark** [RatScanner/RatScanner#79]
When starting RatScanner 2.6.0, it initially would not start, so I went to the 'FAQ' page and installed the .NET 5.0 that was linked; RatScanner then began to tell me that .NET was not installed, and linked me to the 3.1.14 version, which did work with the software.

What I'm trying to say is, the FAQ links to the 5.0 version, but the 3.1.14 is the version that seems to be needed.

**Comment by Blightbuster** [comment]
Thanks ❤️
