### ISSUE TITLE
Not working with russian language

### ISSUE THREAD

**Issue by ApokGG** [RatScanner/RatScanner#86]
Item shown is always incorrect, even search by name. Program settings set on russian. Works if game in english

**Comment by Blightbuster** [comment]
Yes this is indeed a limitation with the new backend, which currently does not support localization. It's on my list of priority fixes though.

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
