### ISSUE TITLE
Incorrect game icons

### ISSUE THREAD

**Issue by YodaGaming** [RatScanner/RatScanner#90]
After running, the game icons were replaced with different objects. I.e. slick armor becoming a P90

**Comment by Shebuka** [comment]
I have the same issue; tryed to clear cache from the app (with eft closed), seems to work well initially with caching rebuilding for all items, well in raid, but after raid the items that were showing perfectly in raid become all messed up in inventory...

**Comment by ageorgewarren** [comment]
Experiencing same issue as well

**Comment by Leskevicius** [comment]
bump

**Comment by Blightbuster** [comment]
Could you please provide steps to replicate this issue?

**Comment by Questler** [comment]
@Blightbuster I think I have the same problem, many is correct but some are wrong

I downloaded, extracted and ran the self contained version and then i set the screen size and use left shift + left mouse to scan.
First time using it and I did not try in raid.

![Wrong image 1](https://user-images.githubusercontent.com/1830170/127194408-c3c80976-432b-409f-a7b4-c2172aa7f947.gif)
![Wrong image 2](https://user-images.githubusercontent.com/1830170/127194416-1374ab6b-689a-43fd-a15d-82484c1b379e.gif)

**Comment by Shebuka** [comment]
@Questler what you are showing is misidentification of objects. What we have is the entire inventory images are messed up. 

After this bug happens clearing the cache from inside app resolve the issue until the next raid. I solved it by removing the app, rebooting and clearing the cache from game launcher, only then it stopped to happen.

**Comment by Shebuka** [comment]
@Blightbuster what caused this to me, I think, is I first uses the app with language set to Russian, then when misidentification happened (a lot with bullets) I switched the game language from Russian to English, misidentification still happened, so I cleared the cache from within the app and after a raid the bug started to happen.

**Comment by Blightbuster** [comment]
Thats it! Clearing the cache while the game is running, certainly causes the bug. I can now fix this in the next release.
Thanks for reporting back ❤️

**Comment by Blightbuster** [comment]
Fixed in [v2.8.0](https://github.com/RatScanner/RatScanner/releases/tag/v2.8.0)
