### ISSUE TITLE
can you add toggle function for more info about items

### ISSUE THREAD

**Issue by ugrolol** [RatScanner/RatScanner#93]
i want to be able to see in program window if item used for any sort of quest or base or something
and make it toogle cos maybe you done all quests already an thats irrelevant

also i want more configurable ui for both recognizion by text and icon
cos for main part im using text option(and only in english cos working really bad with russian)
cos icos doesnt recognized properly half of the time
while text one have only price check for current item under text like could add function to add something like 
price per slot or other info thats in program but would work without opening it everytime and without using always on top

**Comment by namrog84** [comment]
@ugrolol most recent version has added an icon to show if its needed for quest or hideout. Using integration with tarkov tracker. It's super cool!

**Comment by ugrolol** [comment]
got something in last update
